### ISSUE TITLE
Having trouble using with ts-node/ts-node-dev

### ISSUE THREAD

**Issue by barticus** [ShogunPanda/fastify-openapi-docs#3]
Hey!

Plugin looks great, resolves a few issues I have with the fastify-swagger plugin - Thanks!

In my local set up, I original had `"module": "commonjs"` but then after trying to use this plugin i get errors when i try to run locally with ts-node-dev.

Do you have a workaround with this, otherwise can you use a module format more amenable to running with node? For example, heres the [fastify-resty TS Config](https://github.com/FastifyResty/fastify-resty/blob/main/tsconfig.json)

Links for issues related:
[ts-node issue](https://github.com/TypeStrong/ts-node/issues/922)
[stackoverflow post on issue](https://stackoverflow.com/questions/63870080/ts-node-syntaxerror-cannot-use-import-statement-outside-a-module)

If you'd prefer a PR on this, let me know!

**Comment by ShogunPanda** [comment]
Hello!

There are several workaround, depending on how you run your code and depending on your `tsconfig.json`.

If using the `import fastifyOpenapiDocs from 'fastify-openapi-docs'` don't work out of the box, then you have to use the dynamic [import](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_import_expressions) statement, which returns a promise with your module:

```js
const fastify = require('fastify')()

import('fastify-openapi-docs').then(fastifyOpenapiDocs => {
  fastify.register(fastifyOpenapiDocs, /* ... */)

  /* Continue your server bootstrap */
})
```

Now, due to a Typescript bug, even the import might be transpiled to a require and result in a ERR_REQUIRE_ESM error, so in that case you have to use a second workaround:

```js
// Workaround for https://github.com/microsoft/TypeScript/issues/43329
const _importDynamic = new Function('modulePath', 'return import(modulePath)')

const fastify = require('fastify')()

_importDynamic('fastify-openapi-docs').then(fastifyOpenapiDocs => {
  fastify.register(fastifyOpenapiDocs, /* ... */)

  /* Continue your server bootstrap */
})
```

Let me know if this works, otherwise please provide me a minimal reproduction repository.
Hope this helps!
